mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webapp',include('webapp.urls'))
]

webapp/urls.py
from django.urls import path
from . import views
app_name ='webapp'

urlpatterns = [
    path('post_list', views.PostListView.as_view(), name='post_list'),
    path('post_create', views.PostCreateView.as_view(), name='post_create'),
    path('post_detail/<int:pk>/', view=views.PostDetailView.as_view(), name='post_detail'),
    path('post_update/<int:pk>', view=views.PostUpdateView.as_view(), name='post_update'),
    path('post_delete/<int:pk>/', view=views.PostDeleteView.as_view(), name="post_delete"),
    path('calendar/',view=views.Calendar.as_view(), name='calendar'),
    path('calendar/<int:year>/<int:month>/<int:day>/', view=views.Calendar.as_view(), name='calendar'),
    path('', views.MonthCalendar.as_view(), name='month'),
    path('month/<int:year>/<int:month>', view=views.MonthCalendar.as_view(), name='month'),
    path('week/', view=views.WeekCalendar.as_view(), name='week'),
    path('week/<int:year>/<int:month>/<int:day>/', view=views.WeekCalendar.as_view(),  name='week'),
    path('week_with_schedule/', view=views.WeekWithScheduleCalendar.as_view(), name="week_with_schedule"),
    path(
        'week_with_schedule/<int:year>/<int:month>/<int:day>/',
        view=views.WeekWithScheduleCalendar.as_view(),
        name='week_with_schedule'
    )
]

webapp/models.py
import datetime
from django.db import models
from django.utils import timezone
# Create your models here.
class Post(models.Model):
    title = models.CharField("title",max_length=200)
    text = models.TextField("main sentence...")
    date = models.DateTimeField("date", default=timezone.now)

    def __str__(self):
        return self.title

class Schedule(models.Model):
    '''スケジュール'''
    summary = models.CharField('概要',max_length=50)
    description = models.TextField('詳細な説明', blank=True)
    start_time = models.TimeField('開始時刻', default=datetime.time(7,0,0,))
    end_time = models.TimeField('終了時刻', default=datetime.time(7,0,0))
    date = models.DateField('日付') 
    create_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.summary

webapp/forms.py
from django import forms
from webapp.models import Post
from webapp.models import Schedule
class PostCreateForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text')

class BS4ScheduleForm(forms.ModelForm):
    '''Bootstrap model form...'''

    class Meta:
        model = Schedule
        fields = ('summary', 'description', 'start_time', 'end_time')
        widgets = {
            'summary':forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
            }),
            'start_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'end_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
        }
    
    def clean_end_time(self):
        start_time = self.cleaned_data['start_time']
        end_time = self.cleaned_data['end_time']
        if end_time <= start_time:
            raise forms.ValidationError(
                'end_time must be later than start_time...'
            )
        return end_time

webapp/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from webapp.models import Post
from webapp.models import Schedule
from webapp.mixins import MonthCalendarMixin, WeekCalendarMixin,WeekWithScheduleMixin
from .forms import PostCreateForm
from .forms import BS4ScheduleForm
import datetime
# Create your views here.

class PostListView(generic.ListView):
    model = Post

class PostCreateView(generic.CreateView):
    model = Post
    form_class = PostCreateForm
    success_url = reverse_lazy('webapp:post_list')

class PostDetailView(generic.DetailView):
    model = Post

class PostUpdateView(generic.UpdateView):
    model = Post
    form_class = reverse_lazy('webapp:post_detail')

class PostDeleteView(generic.DeleteView):
    model = Post
    success_url = reverse_lazy('webapp:post_list')

class Calendar(mixins.MonthCalendarMixin, mixins.WeekWithScheduleMixin, generic.CreateView):
    '''月間、週間カレンダー、スケージュール登録画面'''
    template_name = 'templates/calendar.html'
    model = Schedule
    data_field = 'date'
    form_class = BS4ScheduleForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        week_calendar_context = self.get_week_calendar()
        month_calendar_context = self.get_month_calendar()
        context.update(week_calendar_context)
        context.update(month_calendar_context)
    
    def form_valid(self, form):
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        if month and year and day:
            date = datetime.date(year=int(year), month=int(month), day=int(day))
        else:
            date = datetime.date.today()
        
        schedule = form.save(commit=False)
        schedule.date = date
        schedule.save()
        return redirect('webapp:calendar', year=date.year, month=date.month, day=date.day)

class MonthCalendar(MonthCalendarMixin):
    template_name = 'templates/month.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        return context

class WeekCalendar(WeekCalendarMixin):
    template_name ='templates/week.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calender_context = self.get_week_calendar()
        context.update(calender_context)
        return context

class WeekWithScheduleCalendar(WeekWithScheduleMixin, generic.TemplateView):
    template_name ='templates/week_with_schedule.html'
    model = Schedule
    date_field = 'date'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_context_data(**kwargs)
        context.update(calendar_context)
        context['week_row'] = zip(
            calendar_context['week_names'],
            calendar_context['week_days'],
            calendar_context['week_day_schedules'].values
        )
        return context

templates/base.html
<!doctype html>
<html lang="ja">
<head>
    <title>sample</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'webapp:post_list' %}">top</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="navbar-nav mr-auto">
                        <a class="nav-link" href="{% url 'webapp:post_create' %}">post</a>
                    </li>
                </ul>
            </div>
            <div class="calendar navbar" id="navbarcalender">
                <ul class="navbar calendar">
                    <li class="navbar calendar">
                        <a class="nav-calendar" href="{% url 'webapp:calendar' %}">calendar</a>
                    </li>
                </ul>

            </div>
        </nav>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/webapp/includes/month.html
<a href="{% url 'app:mycalendar' month_previous.year month_previous.month month_previous.day %}">前月</a>
{{ month_current | date:"Y年m月" }}
<a href="{% url 'app:mycalendar' month_next.year month_next.month month_next.day %}">次月</a>

<table class="table" style="table-layout: fixed;">
    <thead>
    <tr>
        {% for w in week_names %}
            <th>{{ w }}</th>
        {% endfor %}
    </tr>
    </thead
    <tbody>
    {% for week in month_days %}
        <tr>
            {% for day in week %}
                {% if now == day %}
                    <td class="table-success">
                {% else %}
                    <td>
                {% endif %}

                <a href="{% url 'app:mycalendar' day.year day.month day.day %}">{{ day.day }}</a>
                </td>
            {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/webapp/includes/week.html
<a href="{% url 'app:mycalendar' week_previous.year week_previous.month  week_previous.day %}">前週</a>
{{ week_first | date:"Y年m月d日" }}〜{{ week_last | date:"Y年m月d日" }}
<a href="{% url 'app:mycalendar' week_next.year week_next.month  week_next.day %}">次週</a>

<table class="table" style="table-layout: fixed;">
    <tbody>
    <tr>
        {% for day in week_days %}
            {% if now == day %}
                <td class="table-success">
                    {% else %}
                <td>
            {% endif %}
        {% if week_first.month != day.month %}
            {{ day | date:"m/d" }}
        {% else %}
            {{ day.day }}
        {% endif %}
        </td>
        {% endfor %}
    </tr>
    <tr>
        {% for schedules in week_day_schedules.values %}
            <td>
                {% for s in schedules %}
                    {{ s.start_time }} - {{ s.end_time }}<br>
                    {{ s.summary }}<br>
                    {{ s.description | linebreaks }}
                {% endfor %}
            </td>
        {% endfor %}
    </tr>
    </tbody>
</table>

templates/webapp/includes/week_with_schedule.html
{% extends 'webapp/base.html' %}
{% block content %}

    <a href="{% url 'app:week_with_schedule' week_previous.year week_previous.month  week_previous.day %}">前週</a>
    {{ week_first | date:"Y年m月d日" }}〜{{ week_last | date:"Y年m月d日" }}
    <a href="{% url 'app:week_with_schedule' week_next.year week_next.month  week_next.day %}">次週</a>

    <table class="table table-bordered">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for day in week_days %}
                {% if now == day %}
                    <td class="table-success">
                {% else %}
                    <td>
                {% endif %}
            {% if week_first.month != day.month %}
                {{ day | date:"m/d" }}
            {% else %}
                {{ day.day }}
            {% endif %}
            </td>
            {% endfor %}
        </tr>
        <tr>
            {% for schedules in week_day_schedules.values %}
                <td>
                    {% for s in schedules %}
                        {{ s.start_time }} - {{ s.end_time }}<br>
                        {{ s.summary }}<br>
                        {{ s.description | linebreaks }}
                    {% endfor %}
                </td>
            {% endfor %}
        </tr>
        </tbody>
    </table>
{% endblock %}

templates/webapp/post_confirm_delete.html
{% extends 'base.html' %} # 親 template の指定
{% block content %} # 中身の記述開始
<form action="" method="POST">
    <table>
        <tr>
            <th>title</th>
            <td>{{post.title}}</td>
        </tr>
        <tr>
            <th>main sentence...</th>
            <td>{{post.text}}</td>
        </tr>
        <tr>
            <th>date</th>
            <td>{{post.date}}</td>
        </tr>
    </table>
    <p>Do you want to delete this data???</p>
    <button type="submit">delete send</button>
    {% csrf_token %}
</form>
{% endblock %} # 中身の記述終了

templates/webapp/post_detail.html
{% extends 'base.html' %} # 親 template の指定

{% block content %} # 中身の記述開始
<table>
    <tr>
        <th>title</th>
        <td>{{post.title}}</td>
    </tr>
    <tr>
        <th>main sentence...</th>
        <td>{{post.text | linebreaksbr}}</td>
    </tr>
    <tr>
        <th>date</th>
        <td>{{post.date}}</td>
    </tr>
</table>
{% endblock %} # 中身の記述終了

templates/webapp/post_form.html
{% extends 'base.html' %} # 親 template の指定

{% block content %} # 中身の記述開始
<form action="" method="POST">
    <table class="table">
        <tr>
            <th>title</th>
            <td>{{form.title}}</td>
        </tr>
        <tr>
            <th>main sentence...</th>
            <td>{{form.text}}</td>
        </tr>
    </table>
    <button type="submit" class="bth btn-primary">send</button>
    {% csrf_token %}
</form>
{% endblock %} # 中身の記述終了

templates/webapp/post_list.html
{% extends 'base.html' %} # 親 template の指定

{% block content %} # 中身の記述開始
<h1>記事一覧</h1>

<table class="table">
    <thead>
        <tr>
            <th>title</th>
            <th>date</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
      {% for post in post_list %}
      <tr>
        <td><a href="{% url 'webapp:post_detail' post.pk %}">{{post.title}}</a></td>
        <td>{{post.date}}</td>
        <td>
            {% if user.is_superuser %}
              <a herf="{% url 'webapp:post_update' post.pk}">edit</a>
            {% endif %}
        </td>
        <td>
            {% if user.is_superuser %}
              <a href="{% url 'webapp:post_delete' post.pk %}">delete</a>
            {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
</table>
{% endblock %} # 中身の記述終了